# 1. Directory containing the recycle bin
RECYCLE_BIN_ROOT_DIR = "/root/test/.recycle_bin"
# 2. Maximum size of recycle bin (GB)
MAX_CYCLE_BIN_SIZE_GB = 20
# 3. Maximum number of days files can exist in recycle bin
MAX_STORE_DAY = 30

# 4. Check file size and type
CHECK_FILE_SIZE_AND_TYPE = True      #`True` to check, `False` to skip checking
MAX_FILE_SIZE_MB = 1000              # Maximum file size (MB)
IGNORE_FILE_TYPE = [".vpd", ".fsdb"] # File types not allowed in recycle bin

# 5. Daily recycle bin check schedule (Ensures recycle bin always works according to above configurations)
DAILY_SCAN_TIME_24H_IN_HOUR   = 1            #! Hour to scan recycle bin during the day (24h)
RECYCLE_BIN_EXPIRE_YYYYMMDD   = "2026-03-01" #! Recycle bin expiration date (format YYYY-MM-DD).
                                             #! Note: On this date:
                                             #!  - Recycle bin application (RCB) will stop working. The rm command will work like normal delete.
                                             #!  - The RECYCLE_BIN_ROOT_DIR/* directory will be automatically removed.
